google_sheets:
  service_account_path: "config\\gspread\\creds.json"
  spreadsheet_name: "Netikot input"
  input_worksheet_name: "dc data"
  output_worksheet_name: "Results"
  desired_column_names: [ "Brigade","Site Name","IP Address","Company","Camera Port","Camera Password","NVR Port","NVR Password","Modem Port","Modem Password",'Camera Number',"Camera Id" ]
project_setup:
  times:
      check_minutes_diff: 5
      timeout_ping: 30 # Seconds
      checkup_captures_hours: 4
  username: "admin"
  format_datetime: '%Y-%m-%d %H:%M:%S'
